/*TẠO DATABASE*/
CREATE DATABASE SINHVIEN
/*TẠO CÁC TABLE TRONG DATABASE*/
USE SINHVIEN
/*TẠO TABLE HOCSINH*/
CREATE TABLE HOCSINH
(
	ID_HOCSINH VARCHAR(50) PRIMARY KEY,
	ID_LOP VARCHAR(50),
	TEN NVARCHAR(50),
	TUOI TEXT
)
GO
/*TẠO TABLE LỚP*/
CREATE TABLE LOP
(
	ID_LOP VARCHAR(50) PRIMARY KEY,
	ID_NGANH VARCHAR(50),
	MA_LOP INT,
	NAM_HOC INT
)
GO
/*TẠO TABLE NGÀNH*/
CREATE TABLE NGANH
(
	ID_NGANH VARCHAR(50) PRIMARY KEY,
	MA_NGANH INT,
	TEN_NGANH NVARCHAR(50)
)
GO
/*TẠO KHÓA NGOẠI GIỮA CÁC BẢNG*/
ALTER TABLE [LOP] ADD FOREIGN KEY ([ID_NGANH]) REFERENCES [NGANH] ([ID_NGANH])
GO
ALTER TABLE [HOCSINH] ADD FOREIGN KEY ([ID_LOP]) REFERENCES [LOP] ([ID_LOP])
GO
/*THÊM CÁC THÀNH PHẦN VÀO DATABASE*/
USE SINHVIEN
GO
/*THÊM THÀNH PHẦN TABLE NGÀNH*/
INSERT INTO NGANH(ID_NGANH,MA_NGANH,TEN_NGANH) VALUES 
(N'NG004',4,N'PA')
GO
/*THÊM THÀNH PHẦN TABLE LỚP*/
INSERT INTO LOP(ID_LOP,ID_NGANH,MA_LOP,NAM_HOC) VALUES
(N'L006',N'NG004',6,2022)
GO
/*THÊM THÀNH PHẦN TABLE HỌC SINH*/
INSERT INTO HOCSINH(ID_HOCSINH,ID_LOP,TEN,TUOI) VALUES
(N'HS009',N'L006',N'BO',18)
GO
/*LẤY DANH SÁCH SINH VIÊN THEO BỘ LỌC*/
USE SINHVIEN
SELECT HOCSINH.TEN ,HOCSINH.TUOI , LOP.ID_LOP , NGANH.TEN_NGANH , LOP.NAM_HOC FROM HOCSINH ,LOP , NGANH
WHERE LOP.ID_NGANH = NGANH.ID_NGANH AND HOCSINH.ID_LOP = LOP.ID_LOP
/*XEM CHI TIẾT 1 HỌC SINH THEO ID_HOCSINH*/
USE SINHVIEN
SELECT * FROM HOCSINH
WHERE ID_HOCSINH = 'HS001'
/*XÓA 1 THÀNH PHẦN TRONG HỌC SINH*/
USE SINHVIEN
DELETE FROM [HOCSINH]
WHERE ID_HOCSINH = 'HS006'
/*XÓA 1 THÀNH PHẦN TRONG LỚP*/
USE SINHVIEN
DELETE FROM [LOP]
WHERE ID_LOP = 'L006'
/*XÓA 1 THÀNH PHẦN TRONG NGÀNH*/
USE SINHVIEN
DELETE FROM [NGANH]
WHERE ID_NGANH = 'NG004'
/*THAY ĐÔI DƯ LIÊU TRONG HỌC SINH*/
USE SINHVIEN
UPDATE HOCSINH
SET TUOI = 19
WHERE ID_HOCSINH = 'HS003'
/*THAY ĐỔI DỦ LIỆU THONG LỚP*/
USE SINHVIEN
UPDATE LOP
SET NAM_HOC = 2023
WHERE ID_LOP = 'L003'
/*THAY ĐỔI DỦ LIÊU TRONG NGANH*/
USE SINHVIEN
UPDATE NGANH
SET MA_NGANH = 9
WHERE ID_NGANH = 'NG002'

